name: Test Android
on: [push, pull_request]

env:
  ANDROID_NDK_ROOT: $HOME/Library/Android/sdk/ndk/21.4.7075529
  # ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/21.4.7075529
  # By default the new ubuntu-20.04 images use the following ANDROID_NDK_ROOT
  # ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/25.0.8775105

jobs:
  build:
    name: "Build and run connected instrumentation tests"
    runs-on: macos-12
    # runs-on: ubuntu-20.04
    strategy:
      matrix:
        api-level: [ 26, 31 ]
        arch: [ x86_64 ]
    steps:
      - name: Install Android NDK 21.4.7075529
        run: |
          ANDROID_HOME=$HOME/Library/Android/sdk
          SDKMANAGER=$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
          echo y | $SDKMANAGER "ndk;21.4.7075529"

#        run: |
#          ANDROID_ROOT=/usr/local/lib/android
#          ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
#          SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
#          echo "y" | $SDKMANAGER "ndk;21.4.7075529"

      - name: Check out PR branch
        uses: actions/checkout@v2

      - name: Update bdk-ffi git submodule
        run: |
          git submodule set-url bdk-ffi https://github.com/bitcoindevkit/bdk-ffi.git
          git submodule update --init bdk-ffi

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            bdk-ffi/target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Install rust android targets
        run: rustup target add x86_64-linux-android

      - name: Build bdk-android library
        run: ./gradlew :android:buildAndroidLib --exclude-task :android:buildAndroidArmv7Binary --exclude-task :android:buildAndroidAarch64Binary

      - name: Run Connected Instrumentation Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          emulator-options: -dns-server 8.8.8.8
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          script: ./gradlew :android:connectedAndroidTest --console=rich
